ALTER FUNCTION AMSRTONG
(@NUMBER INT)
RETURNS VARCHAR(255)
AS
BEGIN
	DECLARE @FLAG INT=0,
			@REM INT,
			@TOTAL INT=0,
			@TEMP INT=@NUMBER,
			@RESULT VARCHAR(255);
	WHILE(@NUMBER>0)
		BEGIN
			SET @REM=@NUMBER%10;
			SET @TOTAL=@TOTAL+ POWER(@REM,3);
			SET @NUMBER=@NUMBER/10;
		END
	IF(@TOTAL=@TEMP)
		SET @RESULT=CAST(@TEMP AS VARCHAR)+' AMSTRONG';
	ELSE
		SET @RESULT=CAST(@TEMP AS VARCHAR)+' NOT AMSTRONG';
	RETURN @RESULT;
END


PRINT [dbo].[AMSRTONG](153) 
