ALTER FUNCTION PALINDROM
(@NUMBER INT)
RETURNS VARCHAR(250)
AS 
BEGIN
	DECLARE @TEMP INT=@NUMBER,
			@SUM INT=0,
			@FLAG VARCHAR(250);
	WHILE(@NUMBER>0)
		BEGIN
			set @SUM=(@SUM*10) + (@NUMBER%10);
			SET @NUMBER=@NUMBER/10;
		END
	IF(@SUM=@TEMP)
		 SET @FLAG='IS A  PALINDORME';
	ELSE
		 SET @FLAG='NOT A PALINDROME';
	RETURN @FLAG;
END

PRINT [dbo].[PALINDROM](121)