
CREATE TABLE #TEMP(NUMBER INT);
INSERT INTO #TEMP VALUES(5);
SELECT NUMBER FROM #TEMP;
--DELETE FROM  #TEMP WHERE NUMBER=852;

DECLARE @NUMBER INT,
		@OUTPUT VARCHAR(255),
		@TOTAL INT=0;
DECLARE TEM CURSOR FOR SELECT NUMBER FROM #TEMP;
	OPEN TEM
	FETCH NEXT FROM TEM INTO @NUMBER
	WHILE(@@FETCH_STATUS=0)
	BEGIN
		SET @TOTAL=@TOTAL+ @NUMBER;
		FETCH NEXT FROM TEM INTO @NUMBER;
	END
	SET @OUTPUT= 'THE AVERAGE IS '+CAST(@TOTAL AS VARCHAR(255));
	PRINT @OUTPUT
	CLOSE TEM
	DEALLOCATE TEM

