ALTER FUNCTION [dbo].[PRIME]
(@P INT)
RETURNS VARCHAR(255)

AS 

BEGIN
	DECLARE @I INT=2,
			@OUTPUT VARCHAR(255),
			@FLAG INT;
	WHILE(@I<(@P/2))
	BEGIN
		IF (@P%@I=0)
		BEGIN
			SET @FLAG=1;
			BREAK;
		END
		ELSE
			SET @FLAG=0;
			SET @I=@I+1;
	END
	IF(@FLAG=1)
		SET @OUTPUT= CAST(@P AS VARCHAR(150)) +' IS NOT  PRIME';
	ELSE
		SET @OUTPUT= CAST(@P AS VARCHAR(150))+' IS A PRIME';
	RETURN @OUTPUT;
END;


PRINT [dbo].[PRIME](5788159);