ALTER FUNCTION REVERSE(@NUMBER INT )
RETURNS INT 
AS
BEGIN
	DECLARE @TEMP INT=@NUMBER,
			@SUM INT=0,
			@COUNT INT=0;
	WHILE(@TEMP>0)
		BEGIN
			SET @SUM= (@TEMP%10) + @SUM*10;
			SET @TEMP=@TEMP/10;
		END
		RETURN @SUM;
END

PRINT [dbo].[REVERSE](152); 