ALTER FUNCTION SRTINGREVERSE
(@NAME VARCHAR(255))
RETURNS VARCHAR(255)
AS
BEGIN
	DECLARE @I INT=0,
			@REVERSE VARCHAR(255)='',
			@LENGTH INT=LEN(@NAME);
	WHILE(@LENGTH>0)
		BEGIN
			SET @REVERSE=@REVERSE+substring(@NAME,@LENGTH,1);
			SET @LENGTH=@LENGTH-1;
		END
	RETURN @REVERSE;
END

PRINT [dbo].[SRTINGREVERSE]('JEEVAN');